services:
  swoole-php:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: tail -f /dev/null

  sfrpc-go-test:
    image: mybufgen:latest
    build:
      context: .
      dockerfile: tools/protoc-gen-sfrpc/.docker/Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www/tools/protoc-gen-sfrpc
    command: tail -f /dev/null
