<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

declare(strict_types=1);

namespace Wss\Tool\Grpc;

use Sfrpc\Pool\Grpc\ClientContext;
use Sfrpc\Pool\Grpc\SfrpcClientInterface;

interface DomainClientInterface extends SfrpcClientInterface
{
    public function GetInfo(\Wss\Tool\Grpc\GetInfoRequest $request, ?ClientContext $context = null): \Wss\Tool\Grpc\DomainInfo;
}
